# Generated by Django 2.1.1 on 2019-06-18 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190618_1300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relationship',
            options={'verbose_name': 'раздел'},
        ),
    ]
