# Generated by Django 2.1.1 on 2019-06-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AddField(
            model_name='article',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Платный контент'),
        ),
    ]
