# Generated by Django 2.1.1 on 2019-06-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_creator',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='playergameinfo',
            name='tries_number',
            field=models.IntegerField(default=0, verbose_name='Количество попыток'),
        ),
    ]
