# Generated by Django 2.1.1 on 2019-06-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20190626_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='number',
            field=models.IntegerField(null=True, verbose_name='Загаданное число'),
        ),
    ]
