# Generated by Django 2.1.1 on 2019-06-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergameinfo',
            name='is_winner',
            field=models.BooleanField(default=False, verbose_name='Победитель'),
        ),
    ]
