# Generated by Django 2.1.1 on 2019-06-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_game_game_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playergameinfo',
            name='tries_number',
        ),
        migrations.AddField(
            model_name='game',
            name='tries_number',
            field=models.IntegerField(default=0, verbose_name='Количество попыток'),
        ),
    ]
