# Generated by Django 2.1.1 on 2019-06-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20190628_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergameinfo',
            name='tries_number',
            field=models.IntegerField(default=0, verbose_name='Количество попыток'),
        ),
    ]
