# Generated by Django 2.1.1 on 2019-06-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_playergameinfo_tries_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergameinfo',
            name='last_try_number',
            field=models.IntegerField(default=None, verbose_name='Последняя попытка'),
        ),
    ]
