# Generated by Django 2.1.1 on 2019-06-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20190629_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playergameinfo',
            name='last_try_number',
            field=models.IntegerField(null=True, verbose_name='Последняя попытка'),
        ),
    ]
