# Generated by Django 2.1.1 on 2019-06-29 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20190629_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playergameinfo',
            name='last_try_number',
        ),
    ]
